language: generic
sudo: required
services:
  - docker

addons:
  ssh_known_hosts:
    - 140.227.122.189:22
before_install:
  #- docker build -t applingo/docker-react -f Dockerfile.dev .
  - openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  # test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
  - ssh -i ./deploy_key centos@140.227.122.189 pwd

script:
  #- docker run -e CI=true applingo/docker-react npm run test -- --coverage
  - docker run -e CI=true applingo/docker-react .
deploy:
  - provider: script
    skip_cleanup: true
    script: '.travis/deploy.sh'
    on:
      branch: master
